# https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#aws-serverless-application-model-sam
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-guide.html
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Invokes model API'
Parameters:
  InvocationPolicy:
    Type: String
  SDKLayer:
    Type: String
  EndpointName:
    Type: String
Resources:
  mlpredictionservice:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: inference_service
      Description: >-
        Invokes prediction API
      MemorySize: 128
      Timeout: 10
      Layers:
        - !Ref SDKLayer
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref InvocationPolicy
      Environment:
        Variables:
          MODEL_ENDPOINT_ENV: !Ref EndpointName